build:
    tests:
        override:
            -
                command: 'bin/phpunit -c app --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'
checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - app/AppKernel.php
        - app/AppCache.php
        - app/check.php
        - app/SymfonyRequirements.php
        - web/app.php
        - web/app_dev.php
        - web/config.php
        - src/**/*Test.php
        - src/**/Entity/
        - src/**/Repository/
tools:
    php_code_coverage: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    php_cpd: true
    php_mess_detector:
        enabled: true
        config:
            ruleset: ./app/phpmd.xml
    php_code_sniffer:
        enabled: true
        config:
            ruleset: ./app/phpcs.xml
