build:
    tests:
        override:
            -
                command: 'phpunit -c app --coverage-clover some-file'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'
